# build environment
FROM node:18.0.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install --ignore-engines
COPY . ./

# set env
ARG VITE_API_URL
ARG VITE_LOGO
ARG VITE_SCHOOL_NAME
ARG VITE_SCHOOL_DESCRIPTION
ARG VITE_SCHOOL_KEYWORDS
ARG VITE_LANDING_URL
ARG VITE_SPACE_FOLDER
ARG VITE_IMAGE_KIT_ID

ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_LOGO=${VITE_LOGO}
ENV VITE_SCHOOL_NAME=${VITE_SCHOOL_NAME}
ENV VITE_SCHOOL_DESCRIPTION=${VITE_SCHOOL_DESCRIPTION}
ENV VITE_SCHOOL_KEYWORDS=${VITE_SCHOOL_KEYWORDS}
ENV VITE_LANDING_URL=${VITE_LANDING_URL}
ENV VITE_SPACE_FOLDER=${VITE_SPACE_FOLDER}
ENV VITE_IMAGE_KIT_ID=${VITE_IMAGE_KIT_ID}

RUN printf "VITE_API_URL=%s\nVITE_LOGO=%s\nVITE_SCHOOL_NAME=%s\nVITE_SCHOOL_DESCRIPTION=%s\nVITE_SCHOOL_KEYWORDS=%s\nVITE_LANDING_URL=%s\nVITE_SPACE_FOLDER=%s\nVITE_IMAGE_KIT_ID=%s\n" \
	"$VITE_API_URL" "$VITE_LOGO" "$VITE_SCHOOL_NAME" "$VITE_SCHOOL_DESCRIPTION" "$VITE_SCHOOL_KEYWORDS" "$VITE_LANDING_URL" "$VITE_SPACE_FOLDER" "$VITE_IMAGE_KIT_ID" > .env.production

# run build
RUN npm run build


# production environment
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# new
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]