import {
  Article,
  Badge,
  Height,
  HMobiledata,
  Image,
  LocalParking,
  MilitaryTech,
  Newspaper,
  SmartDisplay,
  ViewCarousel,
  TextFields,
  ViewColumn,
} from "@mui/icons-material";

export const BLOCK_TYPES = {
  ROW: "row",
  BANNER: "banner",
  LEFTCARD: "left card",
  RIGHTCARD: "right card",
  COURSES: "courses",
  NEWS: "news",
  NEWS_SECTION: "news section",
  IMAGE: "image",
  VIDEO: "video",
  HEADING: "heading",
  TEXT: "text",
  COMMANDANTS: "commandants",
  STAFFS: "staffs",
  BIG_SPACE: "big space",
  SMALL_SPACE: "small space",
  SUBHEADING: "subheading",
} as const;

export const pageElements = [
  { id: 0, name: "Row", type: BLOCK_TYPES.ROW, icon: ViewColumn },
  { id: 1, name: "Banner", type: BLOCK_TYPES.BANNER, icon: ViewCarousel },
  { id: 2, name: "Left Card", type: BLOCK_TYPES.LEFTCARD, icon: Newspaper },
  { id: 3, name: "Right Card", type: BLOCK_TYPES.RIGHTCARD, icon: Newspaper },
  { id: 4, name: "Courses", type: BLOCK_TYPES.COURSES, icon: Article },
  { id: 5, name: "News", type: BLOCK_TYPES.NEWS, icon: Newspaper },
  {
    id: 6,
    name: "News Section",
    type: BLOCK_TYPES.NEWS_SECTION,
    icon: Newspaper,
  },
  { id: 7, name: "Image", type: BLOCK_TYPES.IMAGE, icon: Image },
  { id: 8, name: "Video", type: BLOCK_TYPES.VIDEO, icon: SmartDisplay },
  { id: 9, name: "Heading", type: BLOCK_TYPES.HEADING, icon: HMobiledata },
  { id: 10, name: "Paragraph", type: BLOCK_TYPES.TEXT, icon: LocalParking },
  {
    id: 11,
    name: "Commandants",
    type: BLOCK_TYPES.COMMANDANTS,
    icon: MilitaryTech,
  },
  { id: 12, name: "Staffs", type: BLOCK_TYPES.STAFFS, icon: Badge },
  { id: 13, name: "Big space", type: BLOCK_TYPES.BIG_SPACE, icon: Height },
  { id: 14, name: "Small space", type: BLOCK_TYPES.SMALL_SPACE, icon: Height },
  { id: 15, name: "Subheading", type: BLOCK_TYPES.SUBHEADING, icon: TextFields },
] as const;