import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithReauth } from "../appBaseQuery";

export const appApi = createApi({
  reducerPath: "appApi",
  baseQuery: baseQueryWithReauth,
  tagTypes: [
    "Courses",
    "Programmes",
    "Faculty",
    "Departments",
    "Levels",
    "Participants",
    "Instructors",
    "Semesters",
    "Sessions",
    "Forms",
    "Posts",
    "Faculties",
    "Lecturers",
    "Students",
    "Admins",
    "Fees",
    "Discounts",
    "Scores",
    "Grades",
    "Students",
    "Applicants",
    "Notes",
    "Quiz",
    "Media",
    "Live",
    "Record",
    "Results",
    "ResultTasks",
    "Transcripts",
    "LiveClasses",
  ],
  endpoints: () => ({}),
});
